foodbook/config/routes.rb
Rails.application.routes.draw do
	root to: "home#index"
	get 'user/index'
	get 'user/show'
	get 'home/index'
	get 'cookbooks/index'
	patch 'save', to: 'recipes#save', as: 'save'
	get 'recipes/index', to: 'recipes#index'
	devise_for :users
	resources :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

foodbook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

foodbook/app/models/cookbook.rb
class Cookbook < ApplicationRecord
	has_many :recipes
end

foodbook/app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :cookbook, optional: true
end

foodbook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cookbook
end

foodbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

foodbook/app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
	def index
		@cookbooks = Cookbook.all
	end

	def show
		@cookbook = Cookbook.find(params[:id])
	end
end

foodbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    free_recipe = Recipe.all
    @recipe = free_recipe.sample
  end
end

foodbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
    	free_recipe = Recipe.all
    	@recipe = free_recipe.sample
    end

    def show
    	@recipe = Recipe.find(params[:id])
    end

    def save
    	recipe = Recipe.find(params[:id])
    	@cookbook.user = current_user
    	recipe.cookbook = cookbook
    	recipe.save!
    	redirect_to cookbook_path
	end

    def recipe_params
		params.require(:recipe)# require makes it so we need to give something, permit makes so no duplicates
	end
end

foodbook/app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!

	def index
    	@users = User.all
  	end

  	def show
    	@user = User.find(params[:id])
  	end
end

foodbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
    	@users = User.all
  	end

  	def show
    	@user = User.find(params[:id])
  	end
end

foodbook/app/helpers/application_helper.rb
module ApplicationHelper
end

foodbook/app/helpers/cookbook_helper.rb
module CookbookHelper
end

foodbook/app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

foodbook/app/helpers/home_helper.rb
module HomeHelper
end

foodbook/app/helpers/recipe_helper.rb
module RecipeHelper
end

foodbook/app/helpers/recipes_helper.rb
module RecipesHelper
end

foodbook/app/helpers/user_helper.rb
module UserHelper
end

foodbook/app/helpers/users_helper.rb
module UsersHelper
end

foodbook/app/views/cookbook/index.html.erb
<h1>Cookbook</h1>

foodbook/app/views/cookbooks/index.html.erb
<h1>Cookbook</h1>

foodbook/app/views/home/index.html.erb
<div class="jumbotron">
  <h2 class="display-3">Welcome to FoodBook</h2>
  <p class="lead">This is a simple Ruby on Rails web app that will allow you to browse and save random recipes. </p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">Begin</a>
  </p>
</div>

foodbook/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

foodbook/app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

foodbook/app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit User Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'Join FoodBook', new_user_registration_path %></li>
<% end %>

foodbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FoodBook" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "FoodBook" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%# Modernizr is required for Zurb Foundation %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <a class="navbar-brand" href="/">Foodbook</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/users/sign_in/">Log In<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_up/">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cookbooks/index">My Cookbook</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/recipes/index">Explore recipes</a>
      </li>
    </ul>
  </div>
</nav>
      <div class="container">
  	<main role="main">
  		<%= render 'layouts/messages' %>
    	<%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
      </div>
  </body>
</html>

foodbook/app/views/recipe/index.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4 col-sm-12">
<h1 class="center-text">Recipes</h1>
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="..." alt="Food pic">
  <div class="card-body">
 
    <h4 class="card-title"> <%= @recipe.dish %></h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <button type="button" class="btn btn-danger">Dislike</button>
    <button type="button" class="btn btn-success">Like</button>

  </div>
</div>
</div>
</div>

foodbook/app/views/recipes/index.html.erb

<div class="row">
  <div class="col-md-4 offset-md-4 col-sm-12">
<h1 class="center-text">Recipes</h1>
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="/assets/recipe-575434_960_720.png" alt="Food pic">
  <div class="card-body">
 
    <h4 class="card-title"> <%= @recipe.dish %> </h4>
    <p class="card-text"> <%= @recipe.instructions %>.</p>
    <button type="button" class="btn btn-danger" VALUE="Reload Page" onClick="history.go(0)">Dislike</button>
    
    <%= button_to "Like", save_path(id: @recipe), :class => "btn btn-success", :method => :patch %>

  </div>
</div>
</div>
</div>